spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/products
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
